spring:
  datasource:
    url: jdbc:h2:mem:bidmatch;MODE=MySQL;DB_CLOSE_DELAY=-1;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true # 로컬에서만 H2 콘솔 켜기

server:
  servlet:
    session:
      cookie:
        secure: false # 로컬은 http라 false